### PR TITLE
More straightforward test running

### PR DESCRIPTION
**Pull request by mjbryant**
Reworks all tests so they don't shell out, and properly install pdfrw test data from PyPI. Tests are now run by:
```bash
$ pip install -r requirements-dev.txt
$ python -m pytest tests
```

Totally fine if you don't want to merge this in. I just thought it might help contributions if the tests were more straightforward.

### CODE REVIEW

**Comment by mjbryant** [comment]
Fixes #143

**Comment by pmaupin** [comment]
The goal of running the examples....

is to make sure that the examples work as people would use them.

E.g. from the command line.

If you're not running the examples from the command line, you're not testing what the example tests were designed to test.

You removed the hash-bang from booklet.py.  So you broke the example, and removed the test that would figure out that you broke the example.  How is that useful?

Also, how/why is it useful to package up the PDFs as a Python package?  If you're submitting PRs to github, presumably you know how to check code out of github.

**Comment by mjbryant** [comment]
Thanks for replying! I was trying to make the tests more understandable and approachable. A few notes:

* The main problem was that the tests weren't runnable in a virtual environment (`pyenv` or `virtualenv`) which is how the vast majority of python developers work nowadays. Removing the shelling out from the tests was both a fix for this, and a move towards a more proper split between testing the _functionality_ of the code, and the I/O, or method of running the code.
* The examples still work if ran as non-executables (e.g. `python -m examples.booklet`). I prefer to run these this way because it avoids confusion with python paths (see [this](https://github.com/asottile/scratch/wiki/PythonPathSadness)), and it doesn't rely on system-installed python (see the above point on virtualenvs). You can keep them as executable files with hash bangs, but that's not really any better than as python modules (that, furthermore, have their code not at the global level so they're actually importable and unit-testable).
* Packaging the PDFs as a python package is also towards the goal of running the tests with one setup (`pip install -r requirements-dev.txt`) and one run (`nosetests tests` or whatever) command, from the top-level directory of your repo. If they're in a python package, all your dependencies for running your tests can be specified in one place. Before, I had to run the tests and see failures/read tracebacks to figure out what the missing dependencies were. Just put all your test dependencies in `requirements-dev.txt`. Install that into your virtualenv and you're ready to go.

If you have no interest in making the tests more user-friendly, that's totally fine. Everyone's got their own style :). I was just trying to get them running and it took me quite a while. Maybe a better change would be putting more explicit instructions front and center.

**Comment by mjbryant** [comment]
For what it's worth, this is just what I did locally to get the tests running. I don't really care how this gets resolved, I just figured it'd be better if the tests were runnable without debugging. 

If I follow the instructions in the readme (without using a virtualenv) to the letter, it only runs two of the tests:

```bash
mbryant@mbp-mbryant bed $ git clone https://github.com/pmaupin/pdfrw
Cloning into 'pdfrw'...
remote: Counting objects: 1291, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1291 (delta 1), reused 1 (delta 1), pack-reused 1286
Receiving objects: 100% (1291/1291), 390.49 KiB | 3.58 MiB/s, done.
Resolving deltas: 100% (837/837), done.
mbryant@mbp-mbryant bed $ cd pdfrw
mbryant@mbp-mbryant pdfrw (master)$ cd tests
mbryant@mbp-mbryant tests (master)$ git clone https://github.com/pmaupin/static_pdfs static_pdfs
Cloning into 'static_pdfs'...
remote: Counting objects: 83, done.
remote: Total 83 (delta 0), reused 0 (delta 0), pack-reused 83
Unpacking objects: 100% (83/83), done.
mbryant@mbp-mbryant tests (master)$ nosetests
..
----------------------------------------------------------------------
Ran 2 tests in 0.009s

OK
```

If I run a specific file, it fails with import errors.

If I run it in a virtualenv, it just fails:
```bash
mbryant@mbp-mbryant bed $ git clone https://github.com/pmaupin/pdfrw
Cloning into 'pdfrw'...
remote: Counting objects: 1291, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1291 (delta 1), reused 1 (delta 1), pack-reused 1286
Receiving objects: 100% (1291/1291), 390.49 KiB | 2.83 MiB/s, done.
Resolving deltas: 100% (837/837), done.
mbryant@mbp-mbryant bed $ cd pdfrw
mbryant@mbp-mbryant pdfrw (master)$ pyenv virtualenv 3.5.4 pdfrw-venv
Requirement already satisfied: setuptools in /Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages
Requirement already satisfied: pip in /Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages
mbryant@mbp-mbryant pdfrw (master)$ pyenv local pdfrw-venv
(pdfrw-venv) mbryant@mbp-mbryant pdfrw (master)$ pip install reportlab nose
Collecting reportlab
  Using cached https://files.pythonhosted.org/packages/87/f9/53b34c58d3735a6df7d5c542bf4de60d699cfa6035e113ca08b3ecdcca3f/reportlab-3.4.0.tar.gz
Collecting nose
  Using cached https://files.pythonhosted.org/packages/15/d8/dd071918c040f50fa1cf80da16423af51ff8ce4a0f2399b7bf8de45ac3d9/nose-1.3.7-py3-none-any.whl
Collecting pillow>=2.4.0 (from reportlab)
  Using cached https://files.pythonhosted.org/packages/63/1b/75e41511d41014e4d6396f8ce4a9a89de1cff98a120e34751bd5877a3141/Pillow-5.2.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: pip>=1.4.1 in /Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages (from reportlab)
Requirement already satisfied: setuptools>=2.2 in /Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages (from reportlab)
Installing collected packages: pillow, reportlab, nose
  Running setup.py install for reportlab ... done
Successfully installed nose-1.3.7 pillow-5.2.0 reportlab-3.4.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pdfrw-venv) mbryant@mbp-mbryant pdfrw (master)$ cd tests
(pdfrw-venv) mbryant@mbp-mbryant tests (master)$ git clone https://github.com/pmaupin/static_pdfs static_pdfs
Cloning into 'static_pdfs'...
remote: Counting objects: 83, done.
remote: Total 83 (delta 0), reused 0 (delta 0), pack-reused 83
Unpacking objects: 100% (83/83), done.
(pdfrw-venv) mbryant@mbp-mbryant tests (master)$ nosetests
E
======================================================================
ERROR: Failure: ImportError (No module named 'static_pdfs')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/mbryant/.pyenv/versions/3.5.4/envs/pdfrw-venv/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/mbryant/.pyenv/versions/3.5.4/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/mbryant/.pyenv/versions/3.5.4/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/mbryant/bed/pdfrw/tests/test_pdfreader_init.py", line 2, in <module>
    import static_pdfs
ImportError: No module named 'static_pdfs'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

**Comment by pmaupin** [comment]
That all makes sense, including supporting virtualenvs and making it easier for other developer/contributors to get started.

_"a move towards a more proper split between testing the functionality of the code, and the I/O, or method of running the code."_

But the examples are for users.  All of the examples I have written are extremely simple.  I've accepted PRs for a few that are more complicated, but most of them are code that is short enough to grok and then cut and paste immediately.  The strategy is that if it's code that is to be called by user code (and it's wrung out/thought out properly), it's in the library.  If it's an example/template for user code, then it goes in an example.

And testing the examples was not done to test the library -- it was done to try to make sure that if a user installs pdfrw and then runs an example, the example just works.  So shelling out is a feature.  Not just from the perspective of making sure the #! is there and works, but also from the perspective of making sure that the library works if it is simply imported from the example, and not "warmed up" by other things importing it first.

I'd love to make it easier for contributors to just get started and run the tests, but not at the cost of inadvertently causing regressions.

Now, obviously, in simpler times, just adding a line to the readme like "install into your system python with setup.py before running tests" would be sufficient, but, as you point out, that won't work for virtualenvs or other non-system installations.

I haven't thought about it enough, but maybe the right answer is to do something like prepending the directory of the currently executing interpreter to the system environment path before shelling out to call the examples.

Thanks,
Pat

**Comment by mjbryant** [comment]
Ah, yeah. I'm not consuming/copy pasting the examples, so I didn't think about this use case. Thanks for clarifying. I'm not sure of the best way to make this work for virtualenvs with keeping the shelling out behaior. I also didn't get the `static_pdfs` thing to work locally, so that's another issue.

**Comment by takluyver** [comment]
It looks like it's shelling out using `sys.executable`, which should already work with virtualenvs. When you're in an env, `sys.executable` points to Python inside that env, so subprocesses are started in the same env.

**Comment by pmaupin** [comment]
Yeah, so the #! isn't even being tested :(

Anyway, this problem is probably the actual path to the library.  Maybe modify os.environ: prepend PYTHONPATH with the directory containing pdfrw...

Also, maybe prepending PATH with sys.executable instead of directly invoking it would work for the majority of cases.  I suppose you could figure out whether 'python' in that directory was a link to the actual interpreter, so in the case it was, you would test the hash-bang, and in the case it wasn't, the test could be successfully executed anyway, the same way it is now.

**Comment by mjbryant** [comment]
Yeah, the problem isn't the wrong executable, the problem is the python
path.

**Pull request closed without merging**
