### PR TITLE
Crypt filters

### PR DESCRIPTION
**Pull request by jonls**
Implements decryption (#48) of streams in PDF files with encryption using the PyCrypto package. The correct crypt filter for string decryption is also made available to the user as `reader.string_crypt_filter` but is not applied automatically. If `decrypt` option is set, the objects will be decrypted (if necessary) before decompressing. This works on a couple of files that I have tested but there are probably files that won't work correctly. ~~In particular, only the global crypt filters are used for now, so if an object specifies a different crypt filter locally it won't work.~~ I had to set a flag on the decrypted `PdfDict`s in the `private` section to remember if it has already been decrypted, otherwise some objects would be twice decrypted when `decrypt` is set. I'm not sure if this is the best approach but it works.

~~The first commit is simply to support a default value on the `PdfDict` `get()` method (like the `dict` `get()` method). It is not strictly necessary but I think it simplifies the code in a few places.~~

~~When I run the round trip tests, a couple of version 1.3 PDFs seem to change hash. I think the difference in the output files is that some objects that were previously indirect objects are now inlined. None of the files that changed hash use encryption as far as I can tell. I'm not sure what exactly caused this change.~~

### CODE REVIEW

**Comment by pmaupin** [comment]
That's awesome!  I won't be able to look seriously at it until next weekend, but it's new functionality that will be great to have.

Four things that I see at a glance:

1) The `PdfDict` class is designed to match closely to a dict in an actual PDF file, so one of the things it does is return `None` if a key does not exist (because semantically, a PDF None is the same as a key not existing in a PDF file.)  So in general, there's no real reason for `get`.

2) The old-style division operator may not work with Python 3.

3) I don't think you want a `PdfName.None`; that would actually be the string `'/None'` which I've never seen used anywhere.  pdfrw matches the regular Python None to the PDF file `'None'`.

4) Most PDFs are not encrypted, and I would prefer a bit of refactoring to minimize the speed hit on unencrypted files.

So, for the dict code, for example:

`cfm = params.get(PdfName.CFM, PdfName.None)`

should probably be:

`cfm = params.CFM`

and:

`key_size = int(doc.Encrypt.get(PdfName.Length, 40)) / 8`

could be:

`key_size = int(doc.Encrypt.Length or 40) // 8`

As you can see, there's probably no real reason to modify `PdfDict.get()` -- the code is shorter and quite readable without it.

And for the encryption, if you could make sure that there's no attempt to run decryption code unless we're decrypting the PDF, that would be great.

Thanks,
Pat

**Comment by pmaupin** [comment]
One more note:  " I had to set a flag on the decrypted PdfDicts in the private section to remember if it has already been decrypted, otherwise some objects would be twice decrypted when decompress is set. I'm not sure if this is the best approach but it works."

I haven't looked at the decryption stuff too much, but when decompressing, we remove any keys from the dictionary that would indicate it's been compressed.  An uncompressed, unencrypted stream should only have a /Length key in the dict.

**Comment by jonls** [comment]
I have made changes for your first two points. For the third point I did mean to use `/None` as the default value for the `/CFM` key. From the specification it seems that the `/CFM` key has a default of `/None`. However, there's no suitable way to handle `/None` anyway so it doesn't really matter if the value is `None` or `/None`.

I have made changes to minimize the impact on non-encrypted files.

The encryption can be specified globally or locally. The locally specified encryption is handled now by looking at the `/Filter` list on the object and decrypting if a `/Crypt` filter is used. This is implemented according to the specification but I have not found any PDFs that use this scheme so I was not able to test it on an actual file. This is done in the same way as decompression so the `/Crypt` is removed from the `/Filter` list if present. If a local crypt filter is specified in this way, the global crypt filter should not be applied. If it is not specified, the global stream filter is applied. In this case, there is no key on the object indicating whether it has been already decrypted or not. I think the issue with double decryption attempts only happen with the `/ObjStm` objects which are first attempted decrypted in the calls to `load_stream_objects()` and then again in `decrypt_all()`. What would be an acceptable way to avoid double encryption if not using a private flag on the object?

I have also made changes so that the `/Encrypt` dictionary is removed after everything is decrypted. This means that the `/Encrypt` dictionary no longer goes into the output file when using `PdfWriter` which otherwise messed up the file since the streams had been decrypted. This works with the files I have tested because they have no encrypted strings (as opposed to streams). It would not work correctly if there are encrypted strings since these are never decrypted automatically.

**Comment by pmaupin** [comment]
I must confess I haven't looked at the decryption in a very long time, and not very rigorously when I did.  I have no ideological objection to private keys on the object if that's the best way to do something -- obviously, I added that capability because sometimes it's required.  So I'll defer to you on the best way to implement that.

The code looks really good; I like the minimized touchpoints in the PdfReader.

Do you have (or can you point me to) example PDFs to add to the regression?  I'd be happy to do that change; the regression procedure isn't all that well documented, but it's mostly functional tests rather than low-level unit-tests, relying on [a bunch of PDFs in a separate repository.](https://github.com/pmaupin/static_pdfs)

Thanks,
Pat

**Comment by pmaupin** [comment]
And just to be clear, when I said earlier that "An uncompressed, unencrypted stream should only have a /Length key in the dict." I wasn't referring to private keys that are used for internal housekeeping.  For those, it can have whatever we need.

**Comment by jonls** [comment]
I tested on this PDF from Intel: https://www-ssl.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-1-manual.html. I also found that USCIS forms are encrypted in the same way: https://www.uscis.gov/forms.

**Comment by tisimst** [comment]
Wow! Thank you, @jonls and @pmaupin for getting this done! I've been needing this for a long time now. Any idea when this update will make it into the python package index? I have lots of files I'd like to test this on that I've had to resort to external utilities (like Ghostscript) to handle the decryption/decompression.

**Pull request merged**
