### PR TITLE
Fix decompression for missing DeflateParms and optimum predictor.

### PR DESCRIPTION
**Pull request by lambdafu**
This patch fixes three cases where pdfrw currently fails (with decompress=True):

* A missing (null) DeflateParms. This is analogous to https://github.com/mozilla/pdf.js/issues/7200
* A png predictor 15 that gets short data (needs to be padded with binary zero).
* A png predictor with colors * bitspercompont != 8 (used for image masks, for example).

### CODE REVIEW

**Comment by pmaupin** [comment]
Thanks for looking into this.

Three things:

1) It fails the integration tests for Python 3.x
2) I don't think you should need the except AttributeError clauses.  In order to impedance-match with how PDF files work a bit better, the pdfrw subclassed dicts should always return null on a non-existent key.
3) If you have a PDF that you can share that fails before the fix and works after the fix, that would be great and we can add it to the test suite.

Thanks,
Pat

**Comment by lambdafu** [comment]
Yeah, we are still on Py2, sorry.  The PDF is a public download from http://unipub.uni-graz.at/download/pdf/1563873?name=3%20H%202%202016 (open access journal, see http://unipub.uni-graz.at/alj/ Vol. 3 H.2).  Here is one test program:

```
from pdfrw.buildxobj import pagexobj
from pdfrw import PdfReader
from pdfrw.errors import PdfNotImplementedError

x=PdfReader("ALJ 2_2016.pdf")
pagexobj(x.pages[1])
```

With the following output:

```
Traceback (most recent call last):
  File "./x.py", line 6, in <module>
    pagexobj(x.pages[1])
  File "pdfrw/buildxobj.py", line 287, in pagexobj
    contents = _build_cache(page.Contents, allow_compressed)
  File "pdfrw/buildxobj.py", line 210, in _build_cache
    keys)
pdfrw.errors.PdfNotImplementedError: Xobjects with compression parameters not supported: ['/Length', '/Filter']
```

And with decompress enabled:

```
from pdfrw.buildxobj import pagexobj
from pdfrw import PdfReader
from pdfrw.errors import PdfNotImplementedError

x=PdfReader("ALJ 2_2016.pdf", decompress=True)
pagexobj(x.pages[1])
```

We got:

```
[WARNING] uncompress.py:46 Not decompressing: cannot use filter '/DCTDecode' with parameters None
[WARNING] uncompress.py:46 Not decompressing: cannot use filter '/DCTDecode' with parameters [{}]
```

The result is a page with content missing (when writing out).

**Comment by pmaupin** [comment]
It looks like the problem is that you are using the old-style divisor operator.  For example:
`columnbytes = ((columns * colors * bpc) + 7) / 8`

**Comment by pmaupin** [comment]
And... The code was that-a-way to start, so there were additional decompression problems on 3.x all along.

**Comment by pmaupin** [comment]
My git-fu is not all that strong, but I have copied your branch, added the division fix for Python 3.x, and added additional decompression tests here:

https://github.com/pmaupin/pdfrw/tree/lambdafu/decompress

Hopefully your git-fu is strong enough to merge that into your pull request...

Unfortunately, one of the tests fails.  Before your changes, attempting to decompress this object would have raised an exception; now it generates a bad graphic.

The bad graphic is generated on the first page of the PDF from:

https://github.com/pmaupin/static_pdfs/raw/master/global/9f98322c243fe67726d56ccfa8e0885b.pdf

In order to run the regression tests:

- cd into the tests directory
- git clone https://github.com/pmaupin/static_pdfs
- ./test_roundtrip.py

This will generate result files into the tmp_results subdirectory.  To do a comparison of any new/changed results, you can run `./checkdiffs.py`

There were two other PDFs that your new code does decompress properly that were not being correctly decompressed before -- if you revert uncompress.py and re-run `test_roundtrip` you will see all the differences.  So that's actually pretty exciting, but if we could figure out how to fix that one graphic before the merge, I'd be happier.

Also, if you think that those graphics don't properly functionally test all of your changes to the decompressor, you can submit pull requests to the static_pdfs, but I'd prefer the examples there to be small, if possible.

To properly add to static_pdfs, copy your pdf into the directory with the PDFs, then cd back up to the tests directory and run `python -m static_pdfs destroy`

Finally, since you've gotten your feet wet and been looking at this -- if you look at the output log from `test_roundtrip.py` you will see that there are several compressed objects that still aren't being dealt with properly (if you feel the need for an extra-credit problem :)

Thanks,
Pat

**Comment by pmaupin** [comment]
Replaced with PR #78

**Pull request closed without merging**
